### ISSUE TITLE
[Bug] KubeVirt Allow-list doesn't always get refreshed

### ISSUE THREAD

**Issue by tlehman** [harvester/pcidevices#19]
Changing the kubevirt list of permitted devices will trigger a change to the `.status.allocatable` value. If you add multiple identical devices, it only counts the first one. Also, if you remove the device, the allocatable list is not updated.

**Proposed solution**: remove the device and then re-add it, to trigger an update.

**Comment by eliaskoromilas** [comment]
My proposed solution is to use [`PCIDevicePlugin`](https://github.com/kubevirt/kubevirt/blob/v0.54.0/pkg/virt-handler/device-manager/pci_device.go#L72) and run our own KubeVirt device plugins, instead of messing with KubeVirt's config.

The lifecycle is similar (if not simpler) and it's fully aligned with KubeVirt's practices. Under the hood the device plugin injects an environment variable, into the `virt-launcher` pod, that specifies the PCI bus addresses for pass-through.

This will also allow us to control exactly which PCI devices are getting advertised (only the claimed ones) and which are not.

**Comment by tlehman** [comment]
Now that 1.1.0 is out, I am going to implement this.
